services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data
  api:
    image: codby/weblive-backend_web
    depends_on:
      - db
    env_file:
      - env
    build: .
    ports:
      - '3001:3000'
    links:
      - db
volumes:
  db:
    driver: local
