name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key

      - name: Deploy to EC2
        env:
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE }}
        run: |
          scp -o StrictHostKeyChecking=no -i private_key -r . ${USER_NAME}@${HOSTNAME}:/home/ubuntu/weblive-backend
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/weblive-backend

            # Install global dependencies.
            sudo npm i -g npm ts-node typescript prisma pm2

            # Install local dependencies, generate Prisma client, push DB changes, and build the project.
            sudo npm ci
            echo "$ENV_FILE_CONTENT" > .env
            sudo npx prisma generate
            sudo npx prisma db push
            sudo npm run build

            # Start or restart the backend service.
            pm2 delete all
            pm2 start dist/main.js --name weblive-backend
          '
