name: Deploy

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${DOCKER_USERNAME}/${DOCKER_IMAGE}:latest
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    env:
      HOSTNAME: ${{ secrets.SSH_HOST }}
      USER_NAME: ${{ secrets.USER_NAME }}
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
      - name: Open SSH And Login docker
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Deploy
        run: |
          '
          cd /home/ubuntu/weblive-api
          sudo echo "${{ secrets.ENV_FILE }}" > .env
          sudo docker pull ${DOCKER_USERNAME}/${DOCKER_IMAGE}:latest
          sudo docker run -p 3000:3000 --network="host" --name ${DOCKER_IMAGE} --env-file .env ${DOCKER_USERNAME}/${DOCKER_IMAGE}:latest
          '
