name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.SSH_HOST}}
          USER_NAME: ${{secrets.USER_NAME}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              sudo rm -r /home/ubuntu/weblive-backend &&
              git clone https://github.com/TheCodby/weblive-backend.git
              cd /home/ubuntu/weblive-backend &&
              sudo npm i &&
              sudo npx prisma generate &&
              sudo npm run build &&
              sudo pm2 delete all &&
              sudo npm run start:prod
              '
