name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    env:
      HOSTNAME: ${{ secrets.SSH_HOST }}
      USER_NAME: ${{ secrets.USER_NAME }}
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
      - name: Open SSH And Login docker
        uses: docker/login-action@v2
        with:
          registry: registry-1.docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Deploy
        run: |
          '
          cd /home/ubuntu/weblive-api
          sudo echo "${{ secrets.ENV_FILE }}" > .env
          sudo docker pull ${DOCKER_USERNAME}/${DOCKER_IMAGE}:latest
          sudo docker run -d -p 3000:3000 --network="host" --env-file .env ${DOCKER_USERNAME}/${DOCKER_IMAGE}:latest --name ${DOCKER_IMAGE}
          '
