name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Containerize-and-Push:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: codby/weblive-backend_web:latest

  Deploy-To-EC2:
    name: Deploy to EC2
    needs: Containerize-and-Push
    runs-on: ubuntu-latest
    env:
      HOSTNAME: ${{ secrets.SSH_HOST }}
      USER_NAME: ${{ secrets.USER_NAME }}
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - uses: actions/checkout@v2
      - uses: astappiev/docker-compose-remote-action@master
        name: Docker-Compose Remote Deployment
        with:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.USER_NAME }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_host_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          docker_compose_prefix: docker-compose
          container_registry_username: ${{ secrets.DOCKER_USERNAME }}
          container_registry_password: ${{ secrets.DOCKER_PASSWORD }}
          container_registry: ${{ secrets.DOCKER_REGISTRY }}
