name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Containerize-and-Push:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: codby/weblive-backend_web:latest

  Deploy-To-EC2:
    name: Deploy to EC2
    needs: Containerize-and-Push
    runs-on: ubuntu-latest
    env:
      HOSTNAME: ${{ secrets.SSH_HOST }}
      USER_NAME: ${{ secrets.USER_NAME }}
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/weblive-api
            sudo echo "${{ secrets.ENV_FILE }}" > .env
            sudo docker pull codby/backend_web:latest || true && sudo docker rm -f weblive-api || true
            sudo docker run -p 3000:3000 --name weblive-api --network="host" --env-file .env codby/weblive-backend_web:latest
          '
