name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
      - name: Build & Deploy
        env:
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            # Now we have got access to EC2 and we will start the deployment.
            if [ -d "/home/ubuntu/weblive-backend" ]; then
              sudo rm -rf /home/ubuntu/weblive-backend
            fi
            sudo git clone https://github.com/TheCodby/weblive-backend.git
            sudo chmod 777 /home/ubuntu/weblive-backend 
            cd /home/ubuntu/weblive-backend 
            sudo echo "${{ secrets.ENV_FILE }}" > .env
            sudo npm i -g ts-node typescript prisma pm2 
            sudo npm i 
            sudo npx prisma generate 
            sudo npx prisma db push 
            sudo npm run build
            pm2 kill
            pm2 start dist/src/main.js --name weblive-backend
          '
