name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            # Now we have got access to EC2 and we will start the deployment.
            if [ -d "/home/ubuntu/weblive-backend" ]; then
              sudo rm -rf /home/ubuntu/weblive-backend
            fi
            sudo git clone https://github.com/TheCodby/weblive-backend.git
            sudo chmod 777 -R /home/ubuntu/weblive-backend &&
            cd /home/ubuntu/weblive-backend &&
            sudo echo "${{ secrets.ENV_FILE }}" > .env
            sudo npm i -g npm &&
            sudo npm i -g ts-node &&
            sudo npm i -g typescript &&
            sudo npm i -g prisma &&
            sudo npm i -g pm2 &&
            sudo npm i &&
            sudo npx prisma generate &&
            sudo npx prisma db push &&
            sudo npm run build &&
            sudo pm2 delete all &&
            sudo npm run start:prod 
            2>&1
          '
