name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            # Now we have got access to EC2 and we will start the deployment.
            if [ -d "/home/ubuntu/weblive-backend" ]; then
              sudo rm -rf /home/ubuntu/weblive-backend
            fi
            sudo git clone https://github.com/TheCodby/weblive-backend.git
            cd /home/ubuntu/weblive-backend &&
            sudo touch .env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env &&
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env  &&
            echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env  &&
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env  &&
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env  &&
            sudo cat .env &&
            sudo npm i &&
            sudo npx prisma generate &&
            sudo npx prisma db push &&
            sudo npm run build &&
            sudo pm2 delete all &&
            sudo npm run start:prod 
            2>&1
          '
